import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import CssBaseline from '@mui/material/CssBaseline';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '@/app/app-theme';
import { ContextProvider } from "@/app/shared/store";
import { AppWrapper } from '@/app/shared/UI-kit/app-wrapper/app-wrapper';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by @N4G1B4T0R'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ContextProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <AppWrapper>{children}</AppWrapper>
            </ThemeProvider>
          </ContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
